---
title: "CodeBook"
author: "Laura Michelena"
date: "10 February 2018"
output: html_document
---

**Experimental design and background:**
---------------------------------------

Human Activity Recognition Using Smartphones Dataset

Version 1.0

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

**

Packages needed
---------------
Besides the basic packages in R, for this code you'll need:

 - dplyr

**


**Raw data:**
-------------

The raw data was download from:
`https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip`
And unzip manually

These are the seven files inside used to create the data:

 - X_test.txt: data from the subject on the test set
 - X_train.txt: data from the subject on the train set
 - y_test.txt: activities (in numbers) corresponding to the test set
 - y_train.txt: activities (in numbers) corresponding to the train set
 - features.txt: variables names in a data.frame
 - subject_test.txt subject id for the test set
 - subject_train.txt: subject id for the train set
 - activity_labels.txt: names corresponding to the activity's number un the y test and train sets.

*How the files are combined is explained in the Processed data section*

*Processed data:**
-------------------

The code is divided in five steps, according to the assignment.


 **Step 1: Merges the training and the test sets to create one data set.**

All the files except features and activity_labels were put toghether using a combination of `cbind` and `rbind`as shown in run_analysis.R and following this instructions:
   
     __________       ___________      ____________
                    |               |  features.txt
     __________       ___________      ____________                    
  subject_train.txt | y_train.txt   |  X_train.txt  
     __________       ___________      ____________                    
  subject_test.txt  | y_test.txt    |  X_test.txt   
     __________       ___________      ____________                    
   
   The resulting data frame had 10299 rows and 563 Vs. All of the observations of all of the 30 subjects in every variable available.
   
   **Step 2: Extracts only the measurements on the mean and standard deviation for each measurement.**

For this step, only de variables ending in mean() or std() where considered; meanFreq() was not taken into acount because is the weighted average of the frequency components, not an average of a measure of an activity; angles() where not taken into acount because they were not vectors, but angles of a vector. 

In consecuense, the final part of this step was a data frame of 10229x68 (Subject, Activity and 66 measurements). 
   

   
 **Step 3: Uses descriptive activity names to name the activities in the data set**

     Merging the tables would reorganice the order of the roads, so I change the names manually with replace () following the numbers in activity_lables.txt. Additinally, following the tidy data info in the videos, everything is lower case and it doesn't include symbols '_'
     
**Step 4: Appropriately labels the data set with descriptive variable names.**

      The instructions on "descriptive variable names" weren't really clear, so there were few options:
      "mean time body aceleration axis x" was explanatory and detailed but had spaces
      "meantimebodyacelerationaxisx" without spaces it was imposible to read.
      "mean.time.body.aceleration.x" was readable but it had a symbols and it waas too long.
      So I settled for:
      "tBodyAccMeanX" it has uppercases but is readable and it doesn't include spaces or symbols.
      
      The codes in this questions removes the parenthesis, removes '-', and spaces.
      
 **Step 5: From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.**
 As explained in several threads in the forum, both a wide or long form of tidy are correct (wide meaning 180 rows and 68 colums, and long 11880 rows and 4 colums) I chose the former because I beleive is easier to work with.
      This was done in three steps:
       1.convert de Vs subject and activity to factors
       2. Use dplyr to group by both of them
       3. summarise the mean of the 66 Vs by each combination of subject*activity.
       
       The result was a data frame that follows the tidy data principles with 180 observarions (each subject by each activity) and 68 Vs. 
       
**

Variable Codes:
---------------
The variables in the data frame where:
    
    1.**subject:** Factor variable with 30 levels. ID of each of the 30 subjects.
    2.**activity:** Factor variable with 6 levels. descriprion of the activity. Levels: laying, sitting, standing, walking, walking up and walking down.
    3 -68: numeric vectors from -1 to +1, named as follows:   
       For each of this 8 measures it include 3 axial values and one mean and standard deviation. Meaning that 8x3x2= 48 variables
 - tBodyAcc: raw signals in time of the body's aceleration measure with the accelerometer in a 3-axial way (X, Y, Z).
 - tGravityAcc: raw signals in time  of the gravity's aceleration measure with the accelerometer in a 3-axial way (X, Y, Z).
 - tBodyAccJerk:  in time, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals, measure with the accelerometer in a 3-axial way (X, Y, Z).
 - tBodyGyro: raw signals in time  of the body's aceleration measure with the gyroscope  in a 3-axial way (X, Y, Z). 
 - tBodyGyroJerk: in time, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals, measure with the gyroscope in a 3-axial way (X, Y, Z).
 - fBodyAcc: raw signals in frecuency of the body's aceleration measure with the accelerometer in a 3-axial way (X, Y, Z).
 - fBodyAccJerk: in frecuency, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals, measure with the accelerometer in a 3-axial way (X, Y, Z).
 - fBodyGyro:  raw signals in frecuency of the body's aceleration measure with the gyroscope  in a 3-axial way (X, Y, Z).

   For each of this 9 measures it inlcudes one mean and one standard deviation. Meaning that 9x2= 18
 - tBodyAccMag: Magnitude of the body's aceleration signals were calculated using the Euclidean norm 
 - tGravityAccMag: Magnitude of the gravity's aceleration signals were calculated using the Euclidean norm 
 - tBodyAccJerkMag: Magnitude of these three-dimensional signals were calculated using the Euclidean norm 
 - tBodyGyroMag: Magnitude of these three-dimensional signals were calculated using the Euclidean norm 
 - tBodyGyroJerkMag: Magnitude of these three-dimensional signals were calculated using the Euclidean norm 
 - fBodyAccMag:Magnitude of these three-dimensional signals were calculated using the Euclidean norm 
 - fBodyAccJerkMag:Magnitude of these three-dimensional signals were calculated using the Euclidean norm    
 - fBodyGyroMag:Magnitude of these three-dimensional signals were calculated using the Euclidean norm  
 - fBodyGyroJerkMag: Magnitude of these three-dimensional signals were calculated using the Euclidean norm 
    

    

      
